baseURL: "https://feusen.github.io/" 
title: Ayden Young
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        #- name: Data
        #  url: data/
        #  weight: 4 
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "This website hosts Ayden Youngs's research, course materials, data, curriculum vitae, and contact info."
    author: Ayden Young
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Ayden Young
          subtitle: "I am a PhD candidate at the University of California at Santa Cruz. My research focuses on the fields of urban and public economics. I currently work as a Graduate Student Instructor (GSI) and a TA throughout the academic year. Before starting my PhD, I was an intern economist at the Federal Deposit Insurance Corporation (FDIC) and a commericial routesetter for First Ascent in Chicago."
          imageUrl: "dripping_in_ice2.jpg"
          imageWidth: 240
          imageHeight: 240
          buttons:
            - name: Papers
              url: papers/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            - name: Courses
              url: courses/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: ayoung_cv.pdf
        - name: Email
          url: mailto:ayoung14@ucsc.edu
        - name: GitHub
          url: https://github.com/feusen
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        - name: Office Hours
          url: officehours/
        #- name: Google Scholar
        #  url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        - name: YouTube
          url: https://www.youtube.com/@aydenyoung2769
        #- name: Twitter
        #  url: https://x.com/pmichaillat
        #- name: Bluesky
        #  url: https://bsky.app/profile/pmichaillat.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Ayden Young"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2